name: CI Pipeline for ML Model

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # <-- Diperbarui ke v4

      - name: Set up Python
        uses: actions/setup-python@v5 # <-- Diperbarui ke v5
        with:
          python-version: '3.10'

      - name: Install MLflow & Dependencies
        run: pip install mlflow==2.19.0 dagshub pandas scikit-learn matplotlib seaborn virtualenv

      - name: Run MLProject Training
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/aksaex/MSML_Proyek_Akhir.mlflow
          MLFLOW_TRACKING_USERNAME: aksaex
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      - name: Get Latest Run ID
        id: get_run_id
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/aksaex/MSML_Proyek_Akhir.mlflow
          MLFLOW_TRACKING_USERNAME: aksaex
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          RUN_ID=$(python -c "from mlflow.tracking import MlflowClient; client = MlflowClient(); runs = client.search_runs(experiment_ids=['0'], order_by=['start_time DESC'], max_results=1); print(runs[0].info.run_id)")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Berhasil mendapatkan Run ID: $RUN_ID"

      - name: Download Model Artifact
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/aksaex/MSML_Proyek_Akhir.mlflow
          MLFLOW_TRACKING_USERNAME: aksaex
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow artifacts download -u "runs:/${{ env.RUN_ID }}/random_forest_model" -d model_artifact

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4 # <-- INI YANG MENYEBABKAN ERROR TADI, sudah diperbarui ke v4
        with:
          name: model-artifact
          path: model_artifact/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # <-- Diperbarui ke v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/aksaex/MSML_Proyek_Akhir.mlflow
          MLFLOW_TRACKING_USERNAME: aksaex
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          echo "Membangun Docker image untuk Run ID: ${{ env.RUN_ID }}"
          mlflow models build-docker -m "runs:/${{ env.RUN_ID }}/random_forest_model" -n ${{ secrets.DOCKER_USERNAME }}/msml-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/msml-model:latest